src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartRepository::class)]
class Cart
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $user = null;

    /**
     * @var Collection<int, CartItem>
     */
    #[ORM\OneToMany(targetEntity: CartItem::class, mappedBy: 'cart', cascade: ['persist', 'remove'])]
    private Collection $cartItems;

    public function __construct()
    {
        $this->cartItems = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;
        if ($user) {
            $user->setCart($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, CartItem>
     */
    public function getCartItems(): Collection
    {
        return $this->cartItems;
    }

    public function addCartItem(CartItem $cartItem): static
    {
        if (!$this->cartItems->contains($cartItem)) {
            $this->cartItems->add($cartItem);
            $cartItem->setCart($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): static
    {
        if ($this->cartItems->removeElement($cartItem)) {
            // set the owning side to null (unless already changed)
            if ($cartItem->getCart() === $this) {
                $cartItem->setCart(null);
            }
        }

        return $this;
    }
}

src/Entity/Coupon.php
<?php

namespace App\Entity;

use App\Repository\CouponRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CouponRepository::class)]
class Coupon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $code = null;


    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $discount_value = null;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?Product $product = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getDiscountValue(): ?string
    {
        return $this->discount_value;
    }

    public function setDiscountValue(string $discount_value): static
    {
        $this->discount_value = $discount_value;

        return $this;
    }
    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $order_number = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 14, scale: 2)]
    private ?string $subtotal = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $discount = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $tax = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $shipping = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 14, scale: 2)]
    private ?string $total = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $billing_address_id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Adress $shipping_address_id = null;

    #[ORM\OneToOne(mappedBy: 'order_id', cascade: ['persist', 'remove'])]
    private ?Payment $payment_id = null;

    #[ORM\ManyToOne]
    private ?Coupon $coupon_id = null;

    #[ORM\OneToMany(mappedBy: 'order_id', targetEntity: OrderItem::class, cascade: ['persist', 'remove'])]
    private Collection $orderItems;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setOrderId($this); // Set the owning side of the relationship
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // Set the owning side to null (unless already changed)
            if ($orderItem->getOrderId() === $this) {
                $orderItem->setOrderId(null);
            }
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderNumber(): ?int
    {
        return $this->order_number;
    }

    public function setOrderNumber(int $order_number): static
    {
        $this->order_number = $order_number;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getSubtotal(): ?string
    {
        return $this->subtotal;
    }

    public function setSubtotal(string $subtotal): static
    {
        $this->subtotal = $subtotal;

        return $this;
    }

    public function getDiscount(): ?string
    {
        return $this->discount;
    }

    public function setDiscount(string $discount): static
    {
        $this->discount = $discount;

        return $this;
    }

    public function getTax(): ?string
    {
        return $this->tax;
    }

    public function setTax(string $tax): static
    {
        $this->tax = $tax;

        return $this;
    }

    public function getShipping(): ?string
    {
        return $this->shipping;
    }

    public function setShipping(string $shipping): static
    {
        $this->shipping = $shipping;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getBillingAddressId(): ?int
    {
        return $this->billing_address_id;
    }

    public function setBillingAddressId(int $billing_address_id): static
    {
        $this->billing_address_id = $billing_address_id;

        return $this;
    }

    public function getShippingAddressId(): ?Adress
    {
        return $this->shipping_address_id;
    }

    public function setShippingAddressId(?Adress $shipping_address_id): static
    {
        $this->shipping_address_id = $shipping_address_id;

        return $this;
    }

    public function getPaymentId(): ?Payment
    {
        return $this->payment_id;
    }

    public function setPaymentId(Payment $payment_id): static
    {
        // set the owning side of the relation if necessary
        if ($payment_id->getOrderId() !== $this) {
            $payment_id->setOrderId($this);
        }

        $this->payment_id = $payment_id;

        return $this;
    }

    public function getCouponId(): ?Coupon
    {
        return $this->coupon_id;
    }

    public function setCouponId(?Coupon $coupon_id): static
    {
        $this->coupon_id = $coupon_id;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::FLOAT, precision: 10, scale: 2)]
    private ?float $price = null;

    #[ORM\Column(type: Types::FLOAT, precision: 5, scale: 2, nullable: true)]
    private ?float $discount_percent = null;

    #[ORM\Column(nullable: true)]
    private ?int $stock_quantity = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: False)]
    private ?Category $category_id = null;

    /**
     * @var Collection<int, WishList>
     */
    #[ORM\ManyToMany(targetEntity: WishList::class, inversedBy: 'products')]
    private Collection $wishlist;

    /**
     * @var Collection<int, ProductImage>
     */
    #[ORM\OneToMany(targetEntity: ProductImage::class, mappedBy: 'product', orphanRemoval: true)]
    private Collection $images;

    public function __construct()
    {
        $this->wishlist = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDiscountPercent(): ?float
    {
        return $this->discount_percent;
    }

    public function setDiscountPercent(?float $discount_percent): static
    {
        $this->discount_percent = $discount_percent;

        return $this;
    }

    public function getStockQuantity(): ?int
    {
        return $this->stock_quantity;
    }

    public function setStockQuantity(?int $stock_quantity): static
    {
        $this->stock_quantity = $stock_quantity;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): static
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * @return Collection<int, wishList>
     */
    public function getWishlist(): Collection
    {
        return $this->wishlist;
    }

    public function addWishlist(wishList $wishlist): static
    {
        if (!$this->wishlist->contains($wishlist)) {
            $this->wishlist->add($wishlist);
        }

        return $this;
    }

    public function removeWishlist(wishList $wishlist): static
    {
        $this->wishlist->removeElement($wishlist);

        return $this;
    }

    /**
     * @return Collection<int, productImage>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ProductImage $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProduct($this);
        }

        return $this;
    }

    public function removeImage(ProductImage $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduct() === $this) {
                $image->setProduct(null);
            }
        }

        return $this;
    }
}

src/Entity/ProductImage.php
<?php

namespace App\Entity;

use App\Repository\ProductImageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductImageRepository::class)]
class ProductImage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?Product $product = null;

    #[ORM\Column(length: 255)]
    private ?string $image_path = null;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private ?bool $is_primary = null;
/*
    #[ORM\ManyToOne(inversedBy: 'images')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;
*/

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function isPrimary(): ?bool
    {
        return $this->is_primary;
    }

    public function setIsPrimary(?bool $is_primary): static
    {
        $this->is_primary = $is_primary;

        return $this;
    }
}

templates/cart/index.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('node_modules/bootstrap/dist/css/bootstrap.css') }}">
    {% block stylsheets %}
    {% endblock %}
    <title>
        {% block title %}
            Welcome
        {% endblock %}
    </title>
</head>
<body>
<div class="container">

    <h1>Header</h1>
    <hr>
    {% block body %}
        <h1>Welcome</h1>
    {% endblock %}
    <hr>
    <h2>Footer</h2>
</div>
<script src="{{ asset('node_modules/bootstrap/dist/js/bootstrap.bundle.js') }}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/cart/list.html.twig
{% extends 'coolbase.html.twig' %}

{% block body %}
    <div class="max-w-6xl mx-auto p-4 font-sans">
        <div class="flex flex-col md:flex-row gap-8">
            <!-- Left side - Cart items -->
            <div class="w-full md:w-2/3">
                <h1 class="text-2xl font-bold mb-6">Your Cart</h1>

                {% if cartItems is empty %}
                    <p class="text-gray-600">Your cart is empty.</p>
                {% else %}
                    <div class="mb-4 pb-2 border-b border-gray-200 grid grid-cols-12 gap-4">
                        <div class="col-span-6 text-sm uppercase text-gray-500">Product</div>
                        <div class="col-span-2 text-sm uppercase text-gray-500 text-center">Quantity</div>
                        <div class="col-span-3 text-sm uppercase text-gray-500 text-right">Price</div>
                        <div class="col-span-1"></div>
                    </div>

                    {% for item in cartItems %}
                        <div class="py-4 border-b border-gray-200 grid grid-cols-12 gap-4 items-center">
                            <div class="col-span-6 flex items-center gap-4">
                                <div class="w-20 h-20 bg-gray-100 rounded-md overflow-hidden">

                                    <a href="/products/{{ item.product.id }}" class="text-decoration-none">
                                        <img src="{% for image in item.product.images %}
                                                {% if image.isPrimary %}
                                                {{ image.imagePath }}
                                                {% endif %}
                                            {% endfor %}" 
                                            onerror="this.onerror=null;this.src='https://i.imgur.com/EJLFNOw.jpg';" class="img-fluid" style="max-height: 7em; border-radius: 10%;">
                                    </a>

                                </div>
                                <div>
                                    <h3 class="font-medium">{{ item.product.name }}</h3>
                                    <p class="text-gray-500 text-sm">{{ item.product.description|slice(0, 40) ~ '...' }}</p>
                                </div>
                            </div>

                            <div class="col-span-2 text-center">
                                {{ item.quantity }}
                            </div>

                            <div class="col-span-3 text-right font-medium">
                                {% set price = item.product.price * (1 - item.product.discountPercent/100) %}
                                {% if order.couponId is defined and order.couponId.product is defined and order.couponId.product == item.product %}
                                    {% set price = price * (1 - order.couponId.discountValue/100) %}
                                {% endif %}
                                {{ (price * item.quantity)|number_format(2, '.', ',') }}DT
                            </div>

                            <div class="col-span-1 text-right">
                                <a href="{{ path('cart_delete', { product_id: item.product.id }) }}" class="text-gray-400 hover:text-red-600">
                                    ✕
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                {% if cartItems is not empty %}
                    <div class="mt-8">
                        <div class="relative">
                            <input type="text" name="coupon" id="coupon" placeholder="Enter coupon code"
                                    class="w-full md:w-72 py-3 px-4 border border-gray-200 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 bg-dark text-white placeholder-gray-400">
                            <button id="couponButton"
                                    class="btn btn-danger float-right" style="background-color: var(--primary-color);">
                                Apply coupon
                            </button>
                        </div>
                    </div>
                {% endif %}
            </div>

            <!-- Right side - Cart total -->
            {% if cartItems is not empty %}
                <div class="w-full md:w-1/3">
                    <div class="bg-gray-900 text-white p-6 rounded-lg">
                        <h2 class="text-2xl font-bold mb-6">Cart total</h2>

                        <div class="space-y-4">
                            <div class="flex justify-between pb-4 border-b border-gray-700">
                                <span>Subtotal</span>
                                <span>{{ total|number_format(2, '.', ',') }}DT</span>
                            </div>

                            <div class="flex justify-between pb-4 border-b border-gray-700">
                                <div>
                                    <div>Shipping Costs</div>
                                </div>
                                <span>19.00DT</span>
                            </div>

                            <div class="flex justify-between pt-2 font-bold">
                                <span>Total</span>
                                <span>{{ (total + 19)|number_format(2, '.', ',') }}DT</span>
                            </div>
                        </div>

                        <a href="{{ path('cart_checkout') }}">
                            <button  class="w-full  text-white rounded-md py-4 font-medium mt-6 hover:bg-gray-100 transition" style="background-color: var(--primary-color);">
                                Continue to Payment
                            </button>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

<script>
    document.getElementById("couponButton").addEventListener('click', function () {
        const btn = document.getElementById("couponButton");
        btn.classList.add("glitter-effect");
        setTimeout(() => btn.classList.remove("glitter-effect"), 1000);

        // this glitter effect is AI generated because CSS why not
        if (!document.getElementById('glitter-effect-style')) {
            const style = document.createElement('style');
            style.id = 'glitter-effect-style';
            style.innerHTML = `
        .glitter-effect {
            position: relative;
            overflow: hidden;
            animation: glitter 1s linear;
        }
        .glitter-effect::after {
            content: '';
            position: absolute;
            left: -75%;
            top: 0;
            width: 50%;
            height: 100%;
            background: linear-gradient(120deg, rgba(255,255,255,0.2) 0%, rgba(255,255,255,0.8) 50%, rgba(255,255,255,0.2) 100%);
            transform: skewX(-20deg);
            animation: glitter-move 1s forwards;
            pointer-events: none;
        }
        @keyframes glitter-move {
            0% { left: -75%; }
            100% { left: 125%; }
        }
        `;
            document.head.appendChild(style);
        }
        //////
        fetch('/cart/apply/' + document.getElementById("coupon").value, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
            },
            body: JSON.stringify({})
        })
            .then(response => response.json())
            .then(data => {
                if (data.message == "success") {
                    //
                }
            })
            .catch(error => console.error('Error:', error));
    });
</script>

{% endblock %}