src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::FLOAT, precision: 10, scale: 2)]
    private ?float $price = null;

    #[ORM\Column(type: Types::FLOAT, precision: 5, scale: 2, nullable: true)]
    private ?float $discount_percent = null;

    #[ORM\Column(nullable: true)]
    private ?int $stock_quantity = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: False)]
    private ?Category $category_id = null;

    /**
     * @var Collection<int, WishList>
     */
    #[ORM\ManyToMany(targetEntity: WishList::class, inversedBy: 'products')]
    private Collection $wishlist;

    /**
     * @var Collection<int, ProductImage>
     */
    #[ORM\OneToMany(targetEntity: ProductImage::class, mappedBy: 'product', orphanRemoval: true)]
    private Collection $images;

    public function __construct()
    {
        $this->wishlist = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDiscountPercent(): ?float
    {
        return $this->discount_percent;
    }

    public function setDiscountPercent(?float $discount_percent): static
    {
        $this->discount_percent = $discount_percent;

        return $this;
    }

    public function getStockQuantity(): ?int
    {
        return $this->stock_quantity;
    }

    public function setStockQuantity(?int $stock_quantity): static
    {
        $this->stock_quantity = $stock_quantity;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): static
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * @return Collection<int, wishList>
     */
    public function getWishlist(): Collection
    {
        return $this->wishlist;
    }

    public function addWishlist(wishList $wishlist): static
    {
        if (!$this->wishlist->contains($wishlist)) {
            $this->wishlist->add($wishlist);
        }

        return $this;
    }

    public function removeWishlist(wishList $wishlist): static
    {
        $this->wishlist->removeElement($wishlist);

        return $this;
    }

    /**
     * @return Collection<int, productImage>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ProductImage $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProduct($this);
        }

        return $this;
    }

    public function removeImage(ProductImage $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduct() === $this) {
                $image->setProduct(null);
            }
        }

        return $this;
    }
}

src/Entity/ProductImage.php
<?php

namespace App\Entity;

use App\Repository\ProductImageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductImageRepository::class)]
class ProductImage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?Product $product = null;

    #[ORM\Column(length: 255)]
    private ?string $image_path = null;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private ?bool $is_primary = null;
/*
    #[ORM\ManyToOne(inversedBy: 'images')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;
*/

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function isPrimary(): ?bool
    {
        return $this->is_primary;
    }

    public function setIsPrimary(?bool $is_primary): static
    {
        $this->is_primary = $is_primary;

        return $this;
    }
}

src/Entity/WishList.php
<?php

namespace App\Entity;

use App\Repository\WishListRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WishListRepository::class)]
class WishList
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    /**
     * @var Collection<int, Product>
     */
    #[ORM\OneToMany(targetEntity: Product::class, mappedBy: 'wishList_id')]
    private Collection $product_id;

    /**
     * @var Collection<int, Product>
     */
    #[ORM\ManyToMany(targetEntity: Product::class, mappedBy: 'wishlist')]
    private Collection $products;

    #[ORM\OneToOne(mappedBy: 'wishlist', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    public function __construct()
    {
        $this->product_id = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProductId(): Collection
    {
        return $this->product_id;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->addWishlist($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            $product->removeWishlist($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setWishlist(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getWishlist() !== $this) {
            $user->setWishlist($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Controller/WishlistController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\WishList;
use App\Service\MailerService;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class WishlistController extends AbstractController
{
    #[Route('/wishlist', name: 'app_wishlist')]
    public function wishlist(): Response
    {
        $user = $this->getUser();
        $products = [];

        // Check if user exists and has a wishlist
        if ($user && $user->getWishList()) {
            $products = $user->getWishList()->getProducts();
        }

        return $this->render('wishlist/index.html.twig', [
            'controller_name' => 'WishlistController',
            'products' => $products,
        ]);
        return $this->render('wishlist/index.html.twig', [
            'controller_name' => 'WishlistController',
            'products' => $this->getUser()->getWishList()->getProducts(),
        ]);

    }
    #[Route('/wishlist/toggle/{id}', name: 'app_wishlist_add')]
    public function addToWishlist(Product $product, ManagerRegistry $manager, MailerService $mailer): JsonResponse
    {   
        $doctrine = $manager->getManager();
        $user = $this->getUser();
        $message = '';
        if ($user){
            $wishlist = $user->getWishList();
            if (!$wishlist) {
                $wishlist = new WishList();
                $wishlist->setUserId($user);
                $doctrine->persist($wishlist);
            }
            if ($wishlist->getProducts()->contains($product)) {
                $wishlist->removeProduct($product);
                $message = 'Product removed from wishlist';
            } else {
                $wishlist->addProduct($product);
                $message = 'Product added to wishlist';
            }
            $doctrine->persist($wishlist);
            $doctrine->flush();
            // Send email notification just for testing mailer service, should not sent notification
            $mailer->sendEmail(
                $user->getEmail(),
                'Wishlist Update',
                "" . $message . " for product: " . $product->getName()
            );
        }
        return new JsonResponse(['success' => true, 'message' => $message]);
    }
}

templates/wishlist/index.html.twig
{% extends 'coolBase.html.twig' %}

{% block title %}GoSport: Wishlist{% endblock %}

{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/nouislider@15.7.0/dist/nouislider.min.css" rel="stylesheet">
{% endblock %}
{% block importmap %}
    <script src="https://cdn.jsdelivr.net/npm/nouislider@15.7.0/dist/nouislider.min.js"></script>
{% endblock %}

{% block sidebarButton %}
{% endblock %}

{% block wishlistBag %}
    {{ parent() }}
{% endblock %}
{% block body %}
    <h1 class="text-center pt-3">Your Wishlist...</h1>
    <br>
    {% if products is empty %}
        <h1 class="text-center">
            ...is empty.
            <br>
            <br><a href="/products">Start</a> adding products to your wishlist!
            <br>
            We will notify you when they are available <br>or when a discount is available!
        </h1>
    {% else %}

    <div class="container-fluid m-4 pt-2 d-flex justify-content-center">
        <table class="table table-striped" id="wishlistTable" style="max-width: 80%;">
            <thead>
                <tr class="sticky-top bg-dark">
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Stock Status</th>
                    <th scope="col">Action</th>
                    <th scope="col">Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr style="font-size: 1.2em;">
                    <td style="text-align: left;">
                    <div class="pt-3 pb-3" style="display: flex; align-items: center; gap: 10px;">
                        <a href="/products/{{ product.id }}" class="text-decoration-none">
                            <img src="{% for image in product.images %}
                                    {% if image.isPrimary %}
                                    {{ image.imagePath }}
                                    {% endif %}
                                {% endfor %}" 
                                onerror="this.onerror=null;this.src='https://i.imgur.com/EJLFNOw.jpg';" class="img-fluid" style="max-height: 7em; border-radius: 10%;">
                        </a>
                        <div>
                            <h1 style="margin: 0;">{{ product.name|capitalize }}</h1>
                            <h2 style="margin: 0; color:RGB(200,200,200);">{{ product.slug }}</h2>
                        </div>
                    </div>
                    </td>
                    <td>{{ (product.price * (100 - product.discountpercent) / 100)|round(2) }}DT</td>
                    <td>
                        {% if product.stockQuantity > 0 %}
                            <span class="text-success">In Stock</span>
                        {% else %}
                            <span class="text-danger">Out of Stock</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if product.stockQuantity > 0 %}
                            <button type="button" class="btn btn-danger btn-sm" id="addToCartBtn{{product.id}}" style="font-size: 1.05em;">
                                Add to Cart
                                <i class="bi bi-bag"></i>
                            </button>
                        {% else %}
                            <a href="/products/{{ product.id }}" class="btn btn-secondary btn-sm" style="font-size: 1.05em;">View Details</a>
                        {% endif %}
                    </td>
                    <td>
                        <button id="deleteBtn{{product.id}}">
                            <i class="bi bi-trash text-white" style="transition: all 0.2s ease; color: var(--primary-color);" onmouseover="this.style.filter='drop-shadow(0 0 3px red)';this.style.color='red'" onmouseout="this.style.filter='none';this.style.color='black'"></i>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
<script>
{% for product in products %}
    document.getElementById("addToCartBtn{{product.id}}").addEventListener('click', function () {
        const btn = document.getElementById("addToCartBtn{{product.id}}");
        btn.classList.add("glitter-effect");
        setTimeout(() => btn.classList.remove("glitter-effect"), 1000);

        // this glitter effect is AI generated because CSS why not
        if (!document.getElementById('glitter-effect-style')) {
            const style = document.createElement('style');
            style.id = 'glitter-effect-style';
            style.innerHTML = `
            .glitter-effect {
                position: relative;
                overflow: hidden;
                animation: glitter 1s linear;
            }
            .glitter-effect::after {
                content: '';
                position: absolute;
                left: -75%;
                top: 0;
                width: 50%;
                height: 100%;
                background: linear-gradient(120deg, rgba(255,255,255,0.2) 0%, rgba(255,255,255,0.8) 50%, rgba(255,255,255,0.2) 100%);
                transform: skewX(-20deg);
                animation: glitter-move 1s forwards;
                pointer-events: none;
            }
            @keyframes glitter-move {
                0% { left: -75%; }
                100% { left: 125%; }
            }
            `;
            document.head.appendChild(style);
        }
        //////
        fetch('/cart/add/{{ product.id }}/1', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
            },
            body: JSON.stringify({})
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                //alert(data.message);
            }
        })
        .catch(error => console.error('Error:', error));
    });
    

    document.getElementById("deleteBtn{{ product.id }}").addEventListener('click', function () {

        document.getElementById("deleteBtn{{ product.id }}").closest('tr').remove();
        if (document.getElementById("wishlistTable").querySelector('tbody').children.length === 0) {
            location.reload();
        }
        fetch('/wishlist/toggle/{{ product.id }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest',
            },
            body: JSON.stringify({})
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                //alert(data.message);
            }
        })
        .catch(error => console.error('Error:', error));
    });
{% endfor %}
</script>
{% endblock %}