src/Entity/Adress.php
<?php

namespace App\Entity;

use App\Repository\AdressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdressRepository::class)]
class Adress
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $street = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column]
    private ?int $postal_code = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_default = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'adress')]
    private Collection $user_id;

    public function __construct()
    {
        $this->user_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isDefault(): ?bool
    {
        return $this->is_default;
    }

    public function setIsDefault(?bool $is_default): static
    {
        $this->is_default = $is_default;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUserId(): Collection
    {
        return $this->user_id;
    }

    public function addUserId(User $userId): static
    {
        if (!$this->user_id->contains($userId)) {
            $this->user_id->add($userId);
            $userId->setAdress($this);
        }

        return $this;
    }

    public function removeUserId(User $userId): static
    {
        if ($this->user_id->removeElement($userId)) {
            // set the owning side to null (unless already changed)
            if ($userId->getAdress() === $this) {
                $userId->setAdress(null);
            }
        }

        return $this;
    }
}

src/Entity/Coupon.php
<?php

namespace App\Entity;

use App\Repository\CouponRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CouponRepository::class)]
class Coupon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $code = null;


    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $discount_value = null;

    #[ORM\ManyToOne(targetEntity: Product::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?Product $product = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getDiscountValue(): ?string
    {
        return $this->discount_value;
    }

    public function setDiscountValue(string $discount_value): static
    {
        $this->discount_value = $discount_value;

        return $this;
    }
    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $order_number = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 14, scale: 2)]
    private ?string $subtotal = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $discount = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $tax = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $shipping = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 14, scale: 2)]
    private ?string $total = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $billing_address_id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Adress $shipping_address_id = null;

    #[ORM\OneToOne(mappedBy: 'order_id', cascade: ['persist', 'remove'])]
    private ?Payment $payment_id = null;

    #[ORM\ManyToOne]
    private ?Coupon $coupon_id = null;

    #[ORM\OneToMany(mappedBy: 'order_id', targetEntity: OrderItem::class, cascade: ['persist', 'remove'])]
    private Collection $orderItems;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setOrderId($this); // Set the owning side of the relationship
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // Set the owning side to null (unless already changed)
            if ($orderItem->getOrderId() === $this) {
                $orderItem->setOrderId(null);
            }
        }

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderNumber(): ?int
    {
        return $this->order_number;
    }

    public function setOrderNumber(int $order_number): static
    {
        $this->order_number = $order_number;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getSubtotal(): ?string
    {
        return $this->subtotal;
    }

    public function setSubtotal(string $subtotal): static
    {
        $this->subtotal = $subtotal;

        return $this;
    }

    public function getDiscount(): ?string
    {
        return $this->discount;
    }

    public function setDiscount(string $discount): static
    {
        $this->discount = $discount;

        return $this;
    }

    public function getTax(): ?string
    {
        return $this->tax;
    }

    public function setTax(string $tax): static
    {
        $this->tax = $tax;

        return $this;
    }

    public function getShipping(): ?string
    {
        return $this->shipping;
    }

    public function setShipping(string $shipping): static
    {
        $this->shipping = $shipping;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getBillingAddressId(): ?int
    {
        return $this->billing_address_id;
    }

    public function setBillingAddressId(int $billing_address_id): static
    {
        $this->billing_address_id = $billing_address_id;

        return $this;
    }

    public function getShippingAddressId(): ?Adress
    {
        return $this->shipping_address_id;
    }

    public function setShippingAddressId(?Adress $shipping_address_id): static
    {
        $this->shipping_address_id = $shipping_address_id;

        return $this;
    }

    public function getPaymentId(): ?Payment
    {
        return $this->payment_id;
    }

    public function setPaymentId(Payment $payment_id): static
    {
        // set the owning side of the relation if necessary
        if ($payment_id->getOrderId() !== $this) {
            $payment_id->setOrderId($this);
        }

        $this->payment_id = $payment_id;

        return $this;
    }

    public function getCouponId(): ?Coupon
    {
        return $this->coupon_id;
    }

    public function setCouponId(?Coupon $coupon_id): static
    {
        $this->coupon_id = $coupon_id;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_UUID', fields: ['uuid'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $uuid = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'user_id')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Adress $adress = null;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    private ?WishList $wishlist = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: Cart::class, cascade: ['persist', 'remove'])]
    private ?Cart $cart = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): static
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->uuid;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getAdress(): ?Adress
    {
        return $this->adress;
    }

    public function setAdress(?Adress $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getWishList(): ?WishList
    {
        return $this->wishlist;
    }

    public function setWishList(?WishList $wishlist): static
    {
        $this->wishlist = $wishlist;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        if ($cart !== null && $cart->getUser() !== $this) {
            $cart->setUser($this);
        }

        return $this;
    }
}

templates/order/checkout.html.twig
{% extends 'coolbase.html.twig' %}

{% block body %}
    <div class="max-w-6xl mx-auto p-4 font-sans">
        <h1 class="text-2xl font-bold mb-8">Checkout</h1>

        <div class="flex flex-col md:flex-row gap-8">
            <!-- Left side - Customer Information -->
            <div class="w-full md:w-2/3">
                <div class="mb-8">
                    <h2 class="text-lg font-medium mb-4">Contact Information</h2>
                    <div class="mb-4">
                        <label for="email" class="block text-sm text-white mb-1">Email address</label>
                        <input type="email" id="email" name="email" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.email }} {% endif %}" required>
                    </div>
                </div>

                <div class="mb-8">
                    <h2 class="text-lg font-medium mb-4">Shipping Information</h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div>
                            <label for="first_name" class="block text-sm text-white mb-1">First name</label>
                            <input type="text" id="first_name" name="first_name" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.firstName }} {% endif %}">
                        </div>
                        <div>
                            <label for="last_name" class="block text-sm text-white mb-1">Last name</label>
                            <input type="text" id="last_name" name="last_name" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.lastName }} {% endif %}">
                        </div>
                    </div>

                    <div class="mb-4">
                        <label for="phone" class="block text-sm text-white mb-1">Phone number</label>
                        <input type="tel" id="phone" name="phone" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.phone }} {% endif %}">
                    </div>

                    <div class="mb-4">
                        <label for="address_line1" class="block text-sm text-white mb-1">Address line</label>
                        <input type="text" id="address_line1" name="address_line1" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.adress.street }} {% endif %}">
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div>
                            <label for="country" class="block text-sm text-white mb-1">Country</label>
                            <div class="relative">
                                <select id="country" name="country" class="appearance-none w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);">
                                    <option value="US">United States</option>
                                    {% for country in countries %}
                                        <option {% if app.user.adress.country == country %} selected {% endif %}>{{ country }}</option>
                                    {% endfor %}
                                </select>
                                <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-3 text-gray-700">
                                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/>
                                    </svg>
                                </div>
                            </div>
                        </div>
                        <div>
                            <label for="city" class="block text-sm text-white mb-1">City</label>
                            <input type="text" id="city" name="city" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.adress.city }} {% endif %}">
                        </div>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label for="state" class="block text-sm text-white mb-1">State</label>
                            <input type="text" id="state" name="state" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.adress.state }} {% endif %}">
                        </div>
                        <div>
                            <label for="postal_code" class="block text-sm text-white mb-1">Postal code</label>
                            <input type="text" id="postal_code" name="postal_code" class="w-full p-3 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" style="background-color: rgb(25,25,25);border: 1px solid rgb(100,100,100);" value="{% if app.user %} {{ app.user.adress.postalCode }} {% endif %}">
                        </div>
                    </div>
                </div>

            </div>


            <!-- Right side - Order Summary -->
            <div class="w-full md:w-1/2 ">
                <div class="bg-gray-900 text-white p-6 rounded-lg ">
                    <h2 class="text-lg font-medium mb-4">Order details</h2>

                    {% if cartItems is not empty %}
                        {% for item in cartItems %}
                            <div class="flex justify-between items-center py-4 border-b border-gray-200">
                                <div class="flex items-center gap-3">
                                    <div class="w-10 h-10 bg-gray-100 rounded-md overflow-hidden">
                                        <a href="/products/{{ item.product.id }}" class="text-decoration-none">
                                            <img src="{% for image in item.product.images %}
                                                    {% if image.isPrimary %}
                                                    {{ image.imagePath }}
                                                    {% endif %}
                                                {% endfor %}" 
                                                onerror="this.onerror=null;this.src='https://i.imgur.com/EJLFNOw.jpg';" class="img-fluid" style="max-height: 7em; border-radius: 10%;">
                                        </a>
                                    </div>
                                    <div>
                                        <div class="font-medium">{{ item.product.name }}</div>

                                    </div>
                                </div>
                                <div class="flex items-center gap-2">
                                    <span class="font-medium">
                                        {% set price = item.product.price * (1 - item.product.discountPercent/100) %}
                                        {% if order is defined and order.couponId is defined and order.couponId.product is defined and order.couponId.product == item.product %}
                                            {% set price = price * (1 - order.couponId.discountValue/100) %}
                                        {% endif %}
                                        {{ price|number_format(2, '.', ',') }}DT x {{ item.quantity }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="py-4 text-center text-gray-500">
                            Your cart is empty
                        </div>
                    {% endif %}

                    <div class="mt-4 space-y-2">
                        <div class="flex justify-between text-white">
                            <span>Subtotal</span>
                            <span>{{ subtotal|number_format(2, '.', ',') }} DT</span>
                        </div>
                        <div class="flex justify-between text-white">
                            <span>Shipping Costs</span>
                            <span>{{ shipping|number_format(2, '.', ',') }} DT</span>
                        </div>
                        <div class="flex justify-between font-bold text-lg pt-2 border-t border-gray-200">
                            <span>Total</span>
                            <span>{{ total|number_format(2, '.', ',') }} DT</span>
                        </div>
                    </div>
                    <a>
                        <button onclick="window.location.href='/payment'" id="confirm-payment-button" type="button"  class="w-full bg-gray-900 text-white rounded-md py-4 font-medium mt-6 hover:bg-black transition">
                            Confirm payment
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Stripe.js SDK -->
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const confirmButton = document.getElementById("confirm-payment-button");
            // Appliquer `--primary-color` au bouton
            confirmButton.style.backgroundColor = "var(--primary-color)";
        });
    </script>


{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All Orders{% endblock %}

{% block body %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>All Orders</h1>
        <a href="{{ path('admin') }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Back to Dashboard
        </a>
    </div>
    
    <div class="card shadow-sm">
        <div class="card-header bg-dark text-white">
            <h5 class="mb-0">Orders Management</h5>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-striped table-hover mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>Order #</th>
                            <th>Date</th>
                            <th>Customer</th>
                            <th>Status</th>
                            <th>Total</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                            <tr>
                                <td><strong>#{{ order.orderNumber }}</strong></td>
                                <td>{{ order.createdAt|date('Y-m-d H:i') }}</td>
                                <td>{{ order.userId.email }}</td>
                                <td class="position-relative">
                                    <span class="badge {% if order.status == 'completed' %}bg-success{% elseif order.status == 'processing' %}bg-warning text-dark{% elseif order.status == 'pending' %}bg-info{% else %}bg-danger{% endif %}">
                                        {{ order.status|capitalize }}
                                    </span>
                                </td>
                                <td><strong>{{ order.total|number_format(2) }} DT</strong></td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a href="{{ path('checkout_success', {'id': order.id}) }}" class="btn btn-sm btn-outline-primary">
                                            <i class="fas fa-eye"></i> View Details
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="6" class="text-center py-4 text-muted">
                                    <i class="fas fa-shopping-cart fa-2x mb-2"></i>
                                    <br>
                                    No orders found
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if orders|length > 0 %}
        <div class="card-footer bg-light">
            <div class="row">
                <div class="col-sm-6">
                    <small class="text-muted">Showing {{ orders|length }} orders</small>
                </div>
                <div class="col-sm-6 text-end">
                    <small class="text-muted">Total Revenue: ${{ orders|reduce((carry, order) => carry + order.total, 0)|number_format(2) }}</small>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/order/list.html.twig
{% extends 'cart/index.html.twig' %}

{% block body %}
    <div class="alert alert-danger">
        Orders List
    </div>
    <ol class="list-group">
        {% for order in orders %}
            <li class="list-group-item">
                {{ order.orderNumber }} : {{ order.total }}

            </li>
        {% endfor %}
    </ol>
{% endblock %}